# Generated by Django 5.2.10 on 2026-01-17 17:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('archived', 'Archived')], default='draft', max_length=32)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes', null=True)),
            ],
            options={
                'verbose_name': 'Count Sheet',
                'verbose_name_plural': 'Count Sheets',
                'ordering': ['-count_date'],
            },
        ),
        migrations.CreateModel(
            name='CountEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_hand_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('calculated_qty_to_order', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=9)),
                ('calculated_order_units', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=9)),
                ('highlight_state', models.CharField(choices=[('red', 'Order Needed'), ('yellow', 'OK'), ('green', 'Over Par')], editable=False, max_length=8)),
                ('notes', models.TextField(blank=True, help_text='Optional notes for the count entry', null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='count_entries', to='inventory.inventoryitem')),
            ],
        ),
    ]
