# Generated by Django 5.2.8 on 2025-11-30 21:47

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountEntryAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_on_hand', models.DecimalField(decimal_places=2, max_digits=9)),
                ('new_on_hand', models.DecimalField(decimal_places=2, max_digits=9)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ('-changed_at',),
            },
        ),
        migrations.CreateModel(
            name='CountSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('mon_wed', 'Mon & Wed'), ('weekly', 'Weekly'), ('biweekly', 'Bi-Weekly'), ('monthly', 'Monthly'), ('semiannual', 'Semi-Annual')], max_length=32)),
                ('count_date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('archived', 'Archived')], default='draft', max_length=32)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('locked', models.BooleanField(default=False, help_text='Once locked, staff can no longer edit counts for this sheet.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-count_date', 'location__name', 'frequency'),
            },
        ),
        migrations.CreateModel(
            name='CountEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_hand_quantity', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Quantity counted by staff in count units.', max_digits=9)),
                ('calculated_qty_to_order', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=9)),
                ('calculated_order_units', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=9)),
                ('highlight_state', models.CharField(choices=[('low', 'Low'), ('near', 'Near Par'), ('ok', 'OK')], default='ok', editable=False, max_length=8)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='count_entries', to='inventory.catalogitem')),
                ('override', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='count_entries', to='locations.locationoverride')),
            ],
            options={
                'ordering': ('sheet__location__name', 'override__display_order', 'item__name'),
            },
        ),
    ]
