# Generated by Django 5.2.10 on 2026-01-17 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('counts', '0001_initial'),
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='countsheet',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='count_sheets_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='countsheet',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='count_sheets', to='locations.location'),
        ),
        migrations.AddField(
            model_name='countsheet',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_count_sheets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='countsheet',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='count_sheets_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='countentry',
            name='sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='counts.countsheet'),
        ),
    ]
