from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import CatalogItemViewSet

# -----------------------------------
# :: DRF Router for Catalog Items
# -----------------------------------

""" 
This registers the `CatalogItemViewSet` with a DRF router to generate API routes for catalog items.
"""
router = DefaultRouter()
router.register(r'catalog-items', CatalogItemViewSet, basename='catalog-item')

# -----------------------------------
# :: URL Pattren
# -----------------------------------

""" 
This includes all routes generated by the DRF router in the URL patterns.
"""
urlpatterns = [
    path('', include(router.urls)),
]
