# Generated by Django 5.2.10 on 2026-01-17 17:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frequency', '0001_initial'),
        ('locations', '0001_initial'),
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('fruit', 'Fruit'), ('dairy', 'Dairy'), ('dry', 'Dry Goods'), ('packaging', 'Packaging'), ('other', 'Other')], default='other', max_length=32)),
                ('count_unit', models.CharField(help_text='Unit jab staff ginti karta hai (bag, tub, each, kg...)', max_length=32)),
                ('order_unit', models.CharField(blank=True, help_text='Unit jab order karte hain (case, box, carton...)', max_length=32)),
                ('pack_size', models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='1 order unit mein kitne count units hote hain', max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('helper_text', models.CharField(blank=True, help_text="Inline helper (e.g. '1 case = 12 bags')", max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('par_level', models.DecimalField(blank=True, decimal_places=2, help_text='Par level (count units mein) — location specific', max_digits=9, null=True)),
                ('order_point', models.DecimalField(blank=True, decimal_places=2, help_text='Low stock alert point (count units)', max_digits=9, null=True)),
                ('storage_location', models.CharField(blank=True, help_text='Item kahan store hota hai (location specific)', max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Mobile app / list mein sorting order')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='vendor.vendor')),
                ('frequency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='frequency.frequency')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='locations.location', verbose_name='Location (blank = global item)')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='vendor.vendor')),
            ],
            options={
                'verbose_name': 'Inventory Item',
                'verbose_name_plural': 'Inventory Items',
                'ordering': ('location__name', 'display_order', 'name'),
                'constraints': [models.CheckConstraint(condition=models.Q(('par_level__gt', 0), ('par_level__isnull', True), _connector='OR'), name='par_level_positive_or_null'), models.CheckConstraint(condition=models.Q(('order_point__lte', models.F('par_level')), ('order_point__isnull', True), ('par_level__isnull', True), _connector='OR'), name='order_point_not_greater_than_par')],
                'unique_together': {('location', 'name')},
            },
        ),
    ]
