# Generated by Django 5.2.8 on 2025-11-30 21:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(choices=[('fruit', 'Fruit'), ('dairy', 'Dairy'), ('dry', 'Dry Goods'), ('packaging', 'Packaging'), ('other', 'Other')], default='other', max_length=32)),
                ('count_unit', models.CharField(help_text='Unit used when staff count the item (e.g., bag, tub, each).', max_length=32)),
                ('order_unit', models.CharField(help_text='Unit used when ordering from vendors (e.g., case, box).', max_length=32)),
                ('pack_size', models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='How many count units are in one order unit. Must be greater than 0.', max_digits=9)),
                ('is_active', models.BooleanField(default=True)),
                ('helper_text', models.CharField(blank=True, help_text="Inline helper text shown to staff (e.g., '1 case = 10 bags').", max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Catalog Item',
                'verbose_name_plural': 'Catalog Items',
                'ordering': ('name',),
            },
        ),
    ]
