# Generated by Django 5.2.8 on 2025-11-30 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(max_length=32)),
                ('count_date', models.DateField()),
                ('export_format', models.CharField(choices=[('pdf', 'PDF'), ('csv', 'CSV')], default='pdf', max_length=8)),
                ('export_url', models.URLField(blank=True, help_text='Optional link to stored export (e.g., cloud storage).')),
                ('payload_snapshot', models.JSONField(blank=True, default=dict, help_text='Lightweight snapshot of the export contents for quick reference.')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('export_notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Report Archive',
                'verbose_name_plural': 'Report Archive',
                'ordering': ('-created_at',),
            },
        ),
    ]
