import { useState, useEffect, useCallback, useMemo } from 'react';
import { useDispatch } from 'react-redux';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import {
  Box,
  Card,
  CardContent,
  Typography,
  Button,
  Chip,
  Skeleton,
  Tooltip,
  IconButton,
} from '@mui/material';
import {
  Add,
  Download,
  Assessment,
  PictureAsPdf,
  LocationOn,
  Person,
} from "@mui/icons-material";

import Header from '../components/Header';
import Table from '../components/Table';
import reportsAPI from '../services/reportsAPI';
import { showNotification } from '../store/slices/uiSlice';

// Custom hook for fetching reports
const useReports = () => {
  const dispatch = useDispatch();
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);

  const fetchReports = useCallback(async () => {
    setLoading(true);
    try {
      const response = await reportsAPI.getAll();
      setReports(response.data.results || response.data || []);
    } catch (error) {
      console.error(error);
      dispatch(showNotification({ message: 'Failed to fetch reports', type: 'error' }));
    } finally {
      setLoading(false);
    }
  }, [dispatch]);

  useEffect(() => {
    fetchReports();
  }, [fetchReports]);

  return { reports, loading, fetchReports };
};

// Helper for safe user display
const getUserDisplay = (user) =>
  user.first_name || user.last_name || user.username || 'Unknown';

// Helper to generate PDF
const generatePDF = (report) => {
  const doc = new jsPDF();

  // Title
  doc.setFontSize(22);
  doc.setTextColor(99, 102, 241);
  doc.text("Purple Banana Inventory Report", 14, 25);

  // Details
  doc.setFontSize(11);
  doc.setTextColor(80, 80, 80);
  const dateStr = new Date(report.count_date).toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });
  doc.text(`Location: ${report.location.name}`, 14, 40);
  doc.text(`Frequency: ${report.frequency}`, 14, 48);
  doc.text(`Count Date: ${dateStr}`, 14, 56);
  doc.text(`Generated by: ${getUserDisplay(report.exported_by)}`, 14, 64);

  // Summary box
  doc.setFillColor(139, 92, 246);
  doc.rect(120, 38, 80, 20, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(12);
  doc.text(`Low Stock Items: ${report.payload_snapshot.low_stock || 0}`, 130, 50);

  // Sample table
  const tableData = [
    ["Banana Purée", "7 bags", "24 bags", "3 cases", "Freezer"],
    ["Strawberry Purée", "5 bags", "18 bags", "3 cases", "Freezer"],
    ["Coconut Milk", "18 cans", "36 cans", "2 cases", "Dry Storage"],
    ["Plastic Cups 16oz", "450 pcs", "1000 pcs", "1 box", "Back Room"],
    ["Lids", "380 pcs", "1000 pcs", "1 box", "Back Room"],
    ["Sugar", "3 bags", "10 bags", "1 case", "Dry Storage"],
  ];

  autoTable(doc, {
    head: [["Item", "Counted", "Par Level", "To Order", "Storage"]],
    body: tableData,
    startY: 75,
    theme: 'grid',
    headStyles: { fillColor: [139, 92, 246], textColor: 255, fontSize: 11 },
    styles: { fontSize: 10, cellPadding: 4 },
    alternateRowStyles: { fillColor: [248, 247, 255] },
  });

  // Footer
  doc.setFontSize(9);
  doc.setTextColor(150, 150, 150);
  doc.text(`Generated on ${new Date().toLocaleString()}`, 14, doc.lastAutoTable.finalY + 10);

  // Filename
  const safeDate = report.count_date.replace(/-/g, '');
  doc.save(`PB_${report.location.name}_${report.frequency}_${safeDate}.pdf`);
};

const ReportsView = () => {
  const dispatch = useDispatch();
  const { reports, loading, fetchReports } = useReports();

  const handleDownload = useCallback((report) => {
    try {
      generatePDF(report);
      dispatch(showNotification({ message: "Report downloaded successfully!", type: "success" }));
    } catch (err) {
      console.error(err);
      dispatch(showNotification({ message: "Failed to download report", type: "error" }));
    }
  }, [dispatch]);

  // Memoized columns for performance
  const columns = useMemo(() => [
    {
      header: 'Report',
      render: ({ frequency, count_date }) => (
        <Box sx={{ display: 'flex', alignItems: 'center', gap: 2 }}>
          <Box sx={{
            width: 50,
            height: 50,
            borderRadius: 2,
            backgroundColor: 'primary.light',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
          }}>
            <PictureAsPdf color="error" />
          </Box>
          <Box>
            <Typography variant="subtitle2" fontWeight={600}>{frequency} Report</Typography>
            <Typography variant="caption" color="text.secondary">{new Date(count_date).toLocaleDateString()}</Typography>
          </Box>
        </Box>
      ),
    },
    {
      header: 'Location',
      render: ({ location }) => (
        <Chip icon={<LocationOn />} label={location.name} size="small" variant="outlined" />
      ),
    },
    {
      header: 'Generated By',
      render: ({ exported_by }) => (
        <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
          <Person fontSize="small" />
          <Typography variant="body2">{getUserDisplay(exported_by)}</Typography>
        </Box>
      ),
    },
  ], []);

  // Stats cards data
  const stats = useMemo(() => ({
    totalReports: reports.length,
    pdfReports: reports.filter(r => r.export_format === 'pdf').length,
    lowStock: reports.reduce((sum, r) => sum + (r.payload_snapshot.low_stock || 0), 0),
  }), [reports]);

  return (
    <Box>
      <Header title="Reports" subtitle="Download your inventory reports" showRefresh onRefresh={fetchReports} />

      {/* Stats Cards */}
      <Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', md: 'repeat(3, 1fr)' }, gap: 3, mb: 4 }}>
        <Card sx={{ background: 'linear-gradient(135deg, #6366f1 0%, #8b5cf6 100%)', color: 'white' }}>
          <CardContent>
            <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, mb: 1 }}>
              <Assessment />
              <Typography variant="overline">Total Reports</Typography>
            </Box>
            <Typography variant="h3" fontWeight={700}>{stats.totalReports}</Typography>
          </CardContent>
        </Card>
        <Card>
          <CardContent>
            <Typography variant="overline" color="text.secondary">PDF Reports</Typography>
            <Typography variant="h3" color="error.main">{stats.pdfReports}</Typography>
          </CardContent>
        </Card>
        <Card>
          <CardContent>
            <Typography variant="overline" color="text.secondary">Low Stock Alerts</Typography>
            <Typography variant="h3" color="warning.main">{stats.lowStock}</Typography>
          </CardContent>
        </Card>
      </Box>

      {/* Reports Table */}
      {loading ? (
        <Box sx={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
          {[...Array(4)].map((_, i) => <Skeleton key={i} height={80} variant="rectangular" sx={{ borderRadius: 2 }} />)}
        </Box>
      ) : reports.length === 0 ? (
        <Card sx={{ textAlign: 'center', py: 8 }}>
          <Assessment sx={{ fontSize: 80, color: 'text.disabled', mb: 2 }} />
          <Typography variant="h5">No reports yet</Typography>
        </Card>
      ) : (
        <Table
          columns={columns}
          data={reports}
          actions={(report) => (
            <Tooltip title="Download PDF">
              <IconButton onClick={() => handleDownload(report)} color="primary">
                <Download />
              </IconButton>
            </Tooltip>
          )}
        />
      )}
    </Box>
  );
};

export default ReportsView;
