import { useState, useEffect, useCallback, useMemo } from "react";
import { useDispatch } from "react-redux";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import {
  Box,
  Card,
  CardContent,
  Typography,
  Chip,
  Skeleton,
  Tooltip,
  IconButton,
} from "@mui/material";
import {
  Download,
  Assessment,
  PictureAsPdf,
  LocationOn,
  CalendarMonth,
  Person,
} from "@mui/icons-material";

import Header from "../components/Header";
import Table from "../components/Table";
import reportsAPI from "../services/reportsAPI";
import { showNotification } from "../store/slices/uiSlice";

// ---------------------- GET USER NAME -----------------------
const getUserDisplay = (user) =>
  user?.first_name || user?.last_name || user?.username || "Unknown";

// ---------------------- FETCH REPORTS HOOK ------------------
const useReports = () => {
  const dispatch = useDispatch();
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);

  const fetchReports = useCallback(async () => {
    setLoading(true);
    try {
      const response = await reportsAPI.getAll();
      // works for DRF paginated or non-paginated
      setReports(response.data.results || response.data || []);
    } catch (error) {
      console.error("Error fetching:", error);
      dispatch(
        showNotification({
          message: "Failed to fetch reports",
          type: "error",
        })
      );
    } finally {
      setLoading(false);
    }
  }, [dispatch]);

  useEffect(() => {
    fetchReports();
  }, [fetchReports]);

  return { reports, loading, fetchReports };
};

// ---------------------- PDF GENERATOR -----------------------
const handleExportPDF = (report, dispatch) => {
  try {
    const doc = new jsPDF("p", "mm", "a4");
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();

    const items = report.payload_snapshot?.items || [];

    const today = new Date().toLocaleString("en-US", {
      weekday: "long",
      year: "numeric",
      month: "long",
      day: "numeric",
      hour: "2-digit",
      minute: "2-digit",
    });

    const userName = report.exported_by?.username || "Unknown";
    const userRole = report.exported_by?.role || "User";

    // ---- Title ----
    doc.setFont("helvetica", "bold");
    doc.setFontSize(26);
    doc.setTextColor(139, 92, 246);
    const title = report.payload_snapshot?.report_title || "Inventory Report";
    doc.text(title, pageWidth / 2, 25, { align: "center" });

    // ---- Subtitle ----
    doc.setFont("helvetica", "normal");
    doc.setFontSize(12);
    doc.setTextColor(80, 80, 80);
    const info = `Generated by: ${userName} (${userRole})  •  ${today}`;
    doc.text(info, pageWidth / 2, 35, { align: "center" });

    doc.setDrawColor(139, 92, 246);
    doc.setLineWidth(0.5);
    doc.line(20, 42, pageWidth - 20, 42);

    // ---- Table ----
    autoTable(doc, {
      startY: 48,
      head: [
        [
          "Item",
          "On Hand",
          "Par",
          "To Order",
          "Category",
          "Storage Location",
          "Counted",
          "Created Date",
        ],
      ],
      body: items.map((item) => [
        item.item_name || "—",
        item.on_hand_quantity || "0",
        item.par_level || "0",
        item.quantity_to_order || "0",
        item.category || "—",
        item.storage_location || "—",
        {
          content: item.count || "0",
          styles: {
            textColor: item.highlight === "Low" ? [239, 68, 68] : [0, 0, 0], // red if low
            fontStyle: item.highlight === "Low" ? "bold" : "normal",
          },
        },
        report.count_date || "—", // Created Date
      ]),
      theme: "grid",
      headStyles: {
        fillColor: [139, 92, 246],
        textColor: 255,
        fontSize: 10,
        fontStyle: "bold",
      },
      styles: {
        fontSize: 9.5,
        cellPadding: 4,
      },
      alternateRowStyles: {
        fillColor: [245, 243, 255],
      },
      margin: { top: 55, left: 14, right: 14 },
      didDrawPage: () => {
        doc.setFontSize(9);
        doc.setTextColor(150, 150, 150);
        doc.text(
          `Purple Banana Inventory • ${new Date().getFullYear()} • Page ${doc.getCurrentPageInfo().pageNumber
          }`,
          14,
          doc.internal.pageSize.getHeight() - 10
        );
      },
    });

    const fileName = `PB_${report.location.name}_${report.frequency}_${report.count_date}.pdf`;
    doc.save(fileName);

    dispatch(
      showNotification({ message: "PDF downloaded successfully!", type: "success" })
    );
  } catch (error) {
    console.error(error);
    dispatch(showNotification({ message: "Failed to generate PDF", type: "error" }));
  }
};

// ---------------------- MAIN COMPONENT -----------------------
const ReportsView = () => {
  const dispatch = useDispatch();
  const { reports, loading, fetchReports } = useReports();

  const columns = useMemo(
    () => [
      {
        header: "Report",
        render: ({ frequency, count_date }) => (
          <Box sx={{ display: "flex", alignItems: "center", gap: 2 }}>
            <Box
              sx={{
                width: 50,
                height: 50,
                borderRadius: 2,
                backgroundColor: "primary.light",
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
              }}
            >
              <PictureAsPdf color="error" />
            </Box>
            <Box>
              <Typography variant="subtitle2" fontWeight={600}>
                {frequency} Report
              </Typography>
              <Typography variant="caption" color="text.secondary">
                {new Date(count_date).toLocaleDateString()}
              </Typography>
            </Box>
          </Box>
        ),
      },
      {
        header: "Created Date",
        render: ({ count_date }) => (
          <Chip
            icon={<CalendarMonth />}
            label={count_date}
            size="small"
            variant="outlined"
          />
        ),
      },
      {
        header: "Location",
        render: ({ location }) => (
          <Chip
            icon={<LocationOn />}
            label={location.name}
            size="small"
            variant="outlined"
          />
        ),
      },
      {
        header: "Generated By",
        render: ({ exported_by }) => (
          <Box sx={{ display: "flex", alignItems: "center", gap: 1 }}>
            <Person fontSize="small" />
            <Typography variant="body2">
              {getUserDisplay(exported_by)}
            </Typography>
          </Box>
        ),
      },
    ],
    []
  );

  return (
    <Box>
      <Header
        title="Reports"
        subtitle="Download your inventory reports"
        showRefresh
        onRefresh={fetchReports}
      />

      {/* Reports Table */}
      {loading ? (
        <Box sx={{ display: "flex", flexDirection: "column", gap: 2 }}>
          {[...Array(4)].map((_, i) => (
            <Skeleton
              key={i}
              height={80}
              variant="rectangular"
              sx={{ borderRadius: 2 }}
            />
          ))}
        </Box>
      ) : reports.length === 0 ? (
        <Card sx={{ textAlign: "center", py: 8 }}>
          <Assessment sx={{ fontSize: 80, color: "text.disabled", mb: 2 }} />
          <Typography variant="h5">No reports yet</Typography>
        </Card>
      ) : (
        <Table
          columns={columns}
          data={reports}
          actions={(report) => (
            <Tooltip title="Download PDF">
              <IconButton
                onClick={() => handleExportPDF(report, dispatch)}
                color="primary"
              >
                <Download />
              </IconButton>
            </Tooltip>
          )}
        />
      )}
    </Box>
  );
};

export default ReportsView;
