# Generated by Django 5.2.10 on 2026-01-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Frequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_day', models.CharField(blank=True, choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], help_text='Start day of the week (for weekly recurrence)', max_length=3, null=True)),
                ('end_day', models.CharField(blank=True, choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], help_text='End day of the week (for weekly recurrence)', max_length=3, null=True)),
                ('recurrence_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='weekly', help_text='Type of recurrence', max_length=10)),
                ('times_run', models.PositiveIntegerField(blank=True, help_text='Configured number of runs per period (e.g., per month for monthly, per year for yearly)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Frequency',
                'verbose_name_plural': 'Frequencies',
                'ordering': ['recurrence_type', 'start_day', 'end_day'],
                'constraints': [models.UniqueConstraint(fields=('recurrence_type', 'start_day', 'end_day', 'times_run'), name='unique_frequency')],
            },
        ),
    ]
