# Generated by Django 5.2.10 on 2026-01-17 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frequency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable location name.', max_length=255, unique=True)),
                ('code', models.SlugField(help_text='Short unique code used in exports and views.', max_length=32, unique=True)),
                ('timezone', models.CharField(default='UTC', help_text='Timezone for scheduling and exports.', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('frequency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='frequency.frequency')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ('name',),
            },
        ),
    ]
