# Generated by Django 5.2.8 on 2025-11-30 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.SlugField(help_text='Short code used in exports and views.', max_length=32, unique=True)),
                ('timezone', models.CharField(default='UTC', help_text='Timezone for scheduling resets and exports.', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='LocationOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('par_level', models.DecimalField(decimal_places=2, help_text='Desired on-hand quantity in count units.', max_digits=9)),
                ('order_point', models.DecimalField(decimal_places=2, help_text='Trigger point for low stock alerts in count units.', max_digits=9)),
                ('frequency', models.CharField(choices=[('mon_wed', 'Mon & Wed'), ('weekly', 'Weekly'), ('biweekly', 'Bi-Weekly'), ('monthly', 'Monthly'), ('semiannual', 'Semi-Annual')], default='weekly', max_length=32)),
                ('storage_location', models.CharField(blank=True, help_text='Where staff can find the item during counts.', max_length=255)),
                ('min_order_qty', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum order quantity in order units (optional).', max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Controls ordering within the mobile views.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_overrides', to='inventory.catalogitem')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='locations.location')),
            ],
            options={
                'verbose_name': 'Location Override',
                'verbose_name_plural': 'Location Overrides',
                'ordering': ('location', 'display_order', 'item__name'),
                'unique_together': {('location', 'item')},
            },
        ),
    ]
